stages:
  upload_zoning_docs:
    cmd: bash zoning/data_processing/upload_zoning_docs.sh
    deps:
    - zoning/data_processing/upload_zoning_docs.sh
    - data/orig-documents
    outs:
    - data/orig_documents_s3_manifest.json
  extract_text:
    cmd: python zoning/data_processing/extract_text.py
    deps:
    - zoning/data_processing/extract_text.py
    - data/orig_documents_s3_manifest.json
    params:
    - extract_text.orig_document_s3_bucket
    outs:
    - data/textract_dataset
  generate_dataset:
    cmd: python zoning/data_processing/generate_dataset.py
    deps:
    - zoning/data_processing/generate_dataset.py
    - data/names_all_towns.json
    - data/textract_dataset
    params:
    - generate_dataset.seed
    - generate_dataset.test_split_frac
    outs:
    - data/hf_dataset
    - data/parquet_dataset
