name: Python CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install PDM
      run: |
        python -m pip install --upgrade pip
        pip install pdm

    - name: Install dependencies with PDM
      run: |
        pdm install

    - name: Install pytest
      run: |
        pdm add --dev pytest

    - name: add dummy openai key
      run: |
        echo "OPENAI_API_KEY=sk-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" > .env

    - name: Run pytest with PDM
      run: |
        pdm run pytest
